name: OERC-Build

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  oerc-integration:
    name: Project Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ '18.x', '20.x' ]
        python-version: [ '3.10', '3.11' ]
        go-version: [ '1.19', '1.20' ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Caching...
        uses: actions/cache@v1
        with:
          path: |
            ~/.npm
            ~/.cache/pip
            client/node_modules
            openapi-generator-cli.jar
          key: ${{ runner.os }}-node-${{ hashFiles('client/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cache-oerc

      - name: npm install
        run: |
          cd client
          npm install --omit=optional

      - name: Build Go Codebase
        run: make build

      - name: Build Npm Codebase
        run: make frontend
