name: OERC

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-license-eye:
    name: Default integration check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Build Codebase
        run: make install

      - name: Build Codebase
        run: make build

      - name: Lint Codebase
        run: make lint

      - name: Test
        run: make test