name: OERC

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-license-eye:
    name: Default integration check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('client/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build Codebase
        run: make install

      - name: npm install and npm run build
        run: |
          cd client
          npm i

      - name: Build Codebase
        run: make build

      - name: Lint Codebase
        run: make lint

      - name: Test
        run: make test