name: OERC-Integration

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  oerc-linting:
    name: Schemathesis Integration Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.8 ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Caching...
        uses: actions/cache@v1
        with:
          path: |
            ~/.cache/pip
            ~/.npm
            client/node_modules
            openapi-generator-cli.jar
          key: ${{ runner.os }}-pip
          restore-keys: |
            ${{ runner.os }}-pip-cache-oerc

      - name: Startup Server
        run: |
          make install
          cd client; npm ci; cd ..
          make build
          docker-compose -f docker-compose-ci.yaml up -d --build

      - name: Run Schemathesis
        run: |
          until [ "`docker inspect -f {{.State.Health.Status}} oerc-server`"=="healthy" ]; do
              sleep 0.5;
          done;
          docker ps && sleep 10 && make integration-test

      - name: Shutdown containers
        if: always()
        run: docker-compose -f docker-compose-ci.yaml down