name: OERC - Linting and Formatting

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  oerc-linting:
    name: Code linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.21'
      - name: Linting
        run: |
          go install github.com/mgechev/revive@latest
          make lint